@startuml
package model {
    component Model
    label observerable as observer
    Model --( observer

    component Logger
    () observer as logger_observer
    Logger -r- logger_observer

    component AStimulus

    Model -r-> AStimulus
}

package view {
    component AView
    () "observer    " as view_observer
    AView -r- view_observer

}

package eeg {
    component TriggerSender
    () observer as trigger_observer
    TriggerSender -- trigger_observer
}

package auditory_tagging {
    component AAudioTagger
}

component Experiment
Experiment --> Model
Experiment --> AView

observer <.. view_observer
observer <.. logger_observer
observer <.. trigger_observer

AStimulus -l-> AAudioTagger
@enduml
