@startuml

class Audio {
    +NDArray[float] array
    +int sampling_frequency
}

package auditory_tagging {
    abstract class AAuditoryTagger {
      #list[ [float, float] ] stimuli_intervals

      +AAuditoryTagger(audio, stimuli)
      +Audio {abstract} create()
    }

    AAuditoryTagger "1" *-[norank]- "1" Audio: audio


    abstract class AAudioTaggerFactory {
      +AAudioTagger {abstract} create_auditory_stimulus(audio: Audio, stimuli_intervals: List[Tuple[float, float])
    }

    package assr_tagger {
        class AMTagger {
          -int frequency
          -Callable[[int, int, int], NDArray[float] tag_generator

          +ASSRTagger(audio, stimuli_intervals, frequency, tag_generator)
          +Audio create()
        }

        class FlippedFMTagger {
          -int frequency

          +FMTagger(audio, stimuli_intervals, frequency)
          +Audio create()

        }

        class AMTaggerFactory {
          -int frequency
          -Callable[[int, int, int], NDArray[float]] tag_generator

          +AMTaggerFactory(frequency, tag_generator)
        }

        class FlippedFMTaggerFactory {
          -int frequency

          +FMTaggerFactory(frequency)
        }
    }

    class NoiseTaggingTagger {
      -Optional[int] seed
      -int bit_width
      -int length_bit
      +Optional[Code] code

      +NoiseTaggingTagger(audio, stimuli_intervals, bits_per_second: int, length_bit, seed)
      +Audio create()
      -void __generate_code()
      -void __get_code(length: int)
    }

    class NoiseTaggingTaggerFactory {
      -int bits_per_second
      -int length_bit
      -Optional[int] seed

      +NoiseTaggingTaggerFactory(bits_per_second, length_bit, seed)
    }

    class RawTagger {
      +Audio create()
    }

    class RawTaggerFactory {
    }

    class ShiftSumTagger {
      -int shift_by

      +ShiftSumTagger(audio, stimuli_intervals, shift_by)
      +Audio create()
    }

    class ShiftSumTaggerFactory {
      -int shift_by
      +ShiftSumTaggerFactory(shift_by)
    }
}

AAuditoryTagger <|-- ShiftSumTagger
AAuditoryTagger <|-- RawTagger
AAuditoryTagger <|-- NoiseTaggingTagger
AAuditoryTagger <|-- AMTagger
AAuditoryTagger <|-- FlippedFMTagger

AAudioTaggerFactory <|-u- ShiftSumTaggerFactory
AAudioTaggerFactory <|-u- AMTaggerFactory
AAudioTaggerFactory <|-u- FlippedFMTaggerFactory
AAudioTaggerFactory <|-u- NoiseTaggingTaggerFactory
AAudioTaggerFactory <|-u- RawTaggerFactory

ShiftSumTagger <.. ShiftSumTaggerFactory: "creates"
AMTagger <.. AMTaggerFactory: "creates"
FlippedFMTagger <.. FlippedFMTaggerFactory: "creates"
NoiseTaggingTagger <.. NoiseTaggingTaggerFactory: "creates"
RawTagger <.. RawTaggerFactory: "creates"


@enduml