@startuml

package auditory_tagging {
    abstract class AAudioTagger {
      #NDArray[float] {abstract} modify_chunk(audio_array_chunk: NDArray[float], fs: int))
      +Audio create(audio, stimuli)
    }


    package assr_tagger {
        class AMTagger {
          -int frequency
          -Callable[[int, int, int], NDArray[float] tag_generator
          -[float, float] signal_interval

          +ASSRTagger(frequency, tag_generator, signal_interval)
        }

        class FMTagger {
          -int frequency
          -float modulation_factor

          +FMTagger(frequency, modulation_factor)
          -(NDArray[Real], NDArray[Real]) {static} extract_amplitudes_phases(numbers: NDArray[Complex])
          -NDArray[Complex] {static} get_complex_number(amplitudes: NDArray[Real], phases: NDArray[Real])
          -NDArray[Real] phases_to_instantaneous_frequencies(phases: NDArray[Real], fs: int)
          -NDArray[Real] instantaneous_frequencies_to_phases(instantaneous_frequencies: NDArray[Real], first_phase: NDArray[Real], fs: int)
          -NDArray[float32] modulate(signal: NDArray[float32])

        }

        class FlippedFMTagger {
          -int frequency
          -int scaling_factor

          +FlippedFMTagger(frequency, scaling_factor)
        }
    }

    class NoiseTaggingTagger {
      -Generator rng
      -int specified_fs
      -int bit_width
      -int length_bit
      +Optional[Code] code

      +NoiseTaggingTagger(fs:int, bits_per_second: int, length_bit, rng)
      -void __generate_code()
      -void __get_code(length: int)
    }

    class RawTagger {
    }

    package shift_taggers {
        class ShiftSumTagger {
          -int shift_by

          +ShiftSumTagger(shift_by)
        }

        class SpectrumShiftTagger {
          -int shift_by

          +SpectrumShiftTagger(shift_by)
        }

        class BinauralTagger {
            -int shift_by
            +BinauralTagger(shift_by)
        }
    }
}

AAudioTagger <|-u- BinauralTagger
AAudioTagger <|-- SpectrumShiftTagger
AAudioTagger <|-- ShiftSumTagger
AAudioTagger <|-- RawTagger
AAudioTagger <|-- NoiseTaggingTagger
AAudioTagger <|-- AMTagger
AAudioTagger <|-- FMTagger
AAudioTagger <|-- FlippedFMTagger



@enduml