@startuml

package model {
    abstract class AObserver {
        +void update(data: Any, identifier: EModelUpdateIdentifier)
    }
}


package eeg {
   enum ETrigger{
     +ETrigger {static} get_trigger(data: Any, identifier: EModelUpdateIdentifier
   }
   note bottom of ETrigger: Contains tha mappings to\nthe actual trigger numbers\nsent

    abstract class TriggerSender {
        #void {abstract} send_trigger(trigger: ETrigger)
    }

   class BittiumTriggerSender<<Observer>> {
     -IParallelPort parallel_port
     -int trigger_duration_s
     +BittiumTriggerSender(parallel_port, trigger_duration_s)
     #void send_trigger(trigger: ETrigger)
   }
}
TriggerSender -u-|> AObserver
BittiumTriggerSender -r-|> TriggerSender
BittiumTriggerSender ..> ETrigger: "uses"


@enduml